name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hello Bhupesh"
          echo "Learning GitHub Actions!"
      - name: Print goodbye
        run: echo "Bye!"
